"use client";
import {useCallback,useEffect,useState} from "react";
import QRCode from "qrcode";
import {Users, Ticket, Megaphone, Search, Plus, ShieldCheck, Copy, ArrowLeft, RefreshCw, Menu, X, Trophy, Settings, LogOut} from "lucide-react";
type Member={id:string;firstName:string;lastName:string;phone:string;email:string;status:string;expiresAt:string;token:string;createdAt:string};
type Promo={code:string;campaign:string;memberId:string|null;status:string;createdAt:string};
type Update={id:number;title:string;body:string;createdAt:string};
type MemberNotification={id:number;memberId:string;title:string;body:string;reply:string;repliedAt:string;createdAt:string};
type Data={members:Member[];promos:Promo[];updates:Update[];notifications:MemberNotification[]};
const empty:Data={members:[],promos:[],updates:[],notifications:[]};
function Badge({status}:{status:string}){return <span className={"badge "+status}>{status}</span>}
export default function Home(){
 const [tab,setTab]=useState<"members"|"promos"|"updates">("members"),[data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<Member|null>(null),[qr,setQr]=useState(""),[showForm,setShowForm]=useState(false),[mobileMenu,setMobileMenu]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/data",{cache:"no-store"});const v=await r.json();if(!r.ok)throw Error(v.error);setData(v);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load records")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}};
  register({name:"list_members",title:"List club members",description:"Read current member names, IDs and statuses from the directory.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const r=await fetch("/api/data",{cache:"no-store"});if(!r.ok)throw Error("Directory unavailable");const d=await r.json() as Data;return d.members.map(m=>({id:m.id,name:m.firstName+" "+m.lastName,status:m.status}))}});
  register({name:"create_member",title:"Create club member",description:"Add a named member to the club registry with pending status.",inputSchema:{type:"object",properties:{firstName:{type:"string"},lastName:{type:"string"},phone:{type:"string"},email:{type:"string"}},required:["firstName","lastName"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const v=input as Record<string,unknown>;if(typeof v.firstName!=="string"||!v.firstName.trim()||typeof v.lastName!=="string"||!v.lastName.trim())throw Error("First and last names are required");const r=await fetch("/api/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"member",...v})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();return {id:d.id,status:"pending"}}});
  return ()=>controller.abort();
 },[load]);
 useEffect(()=>{if(!selected)return;QRCode.toDataURL(location.origin+"/verify/"+selected.token,{width:256,margin:2,color:{dark:"#102b5a",light:"#ffffff"}}).then(setQr).catch(()=>setQr(""))},[selected]);
 async function send(payload:Record<string,unknown>,success:string){setError("");setNotice("");try{const r=await fetch("/api/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const v=await r.json();if(!r.ok)throw Error(v.error);setNotice(payload.action==="promos"?v.added+" codes added; "+v.duplicates+" duplicates skipped.":success);await load();return true}catch(e){setError(e instanceof Error?e.message:"Could not save");return false}}
 const list=data.members.filter(m=>(m.id+" "+m.firstName+" "+m.lastName+" "+m.phone).toLowerCase().includes(query.toLowerCase()));
 return <div className="app">
  <aside className="rail"><div className="identity"><div className="crest">TR</div><div><strong>TOWNSHIP<br/>ROLLERS FC</strong><small>MEMBERSHIP OFFICE</small></div></div>
   <nav aria-label="Sections"><button className={tab==="members"?"on":""} onClick={()=>{setTab("members");setSelected(null)}}><Users size={19}/> Members</button><button className={tab==="promos"?"on":""} onClick={()=>{setTab("promos");setSelected(null)}}><Ticket size={19}/> Promotional codes</button><button className={tab==="updates"?"on":""} onClick={()=>{setTab("updates");setSelected(null)}}><Megaphone size={19}/> Communiqués</button></nav>
   <div className="rail-foot"><a href="/office" style={{color:"#ffd15a",display:"block",marginBottom:14}}>Payments & match office →</a><a href="/club" style={{color:"#ffd15a",display:"block",marginBottom:14}}>Club page →</a><button className="rail-signout" onClick={async()=>{await fetch("/api/admin-pin",{method:"DELETE"});location.assign("/signout-with-chatgpt?return_to=/")}}>Sign out →</button><span className="tiny-dot"/> Club administration <small>2026–2027 season</small></div>
  </aside>
  <main className="main">
   <header className="top"><div className="mobile-brand"><div className="crest">TR</div><b>Township Rollers</b></div><span>CLUB MEMBERSHIP SYSTEM</span><span className="top-season">2026 / 2027</span></header>
   <div className="content">
    {selected?<><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={17}/> Back to members</button><div className="page-head"><div><p className="eyebrow">MEMBER RECORD</p><h1>{selected.firstName} {selected.lastName}</h1><p className="sub">{selected.id} · Joined {new Date(selected.createdAt).toLocaleDateString()}</p></div><div className="member-record-actions"><Badge status={selected.status}/><button className="primary" onClick={()=>{const message=window.prompt(`Notification for ${selected.firstName} ${selected.lastName}`);if(message?.trim())void send({action:"member-notification",memberId:selected.id,title:"Membership notification",body:message.trim()},"Notification sent")}}>Send notification</button></div></div>
      <div className="detail-grid"><section className="panel"><h2>Membership details</h2><dl className="details"><div><dt>Member ID</dt><dd>{selected.id}</dd></div><div><dt>Phone</dt><dd>{selected.phone||"—"}</dd></div><div><dt>Email</dt><dd>{selected.email||"—"}</dd></div><div><dt>Expiry</dt><dd>{selected.expiresAt||"Not set"}</dd></div></dl><label className="field">Membership status<select value={selected.status} onChange={async e=>{const status=e.target.value;if(await send({action:"status",id:selected.id,status},"Status updated"))setSelected({...selected,status})}}><option value="pending">Pending</option><option value="active">Active</option><option value="expired">Expired</option><option value="suspended">Suspended</option></select></label><form className="expiry-edit" onSubmit={async e=>{e.preventDefault();const expiresAt=String(new FormData(e.currentTarget).get("expiresAt")||"");if(await send({action:"expiry",id:selected.id,expiresAt},"Expiry date updated"))setSelected({...selected,expiresAt})}}><label className="field">Expiry date<input name="expiresAt" type="date" key={selected.expiresAt} defaultValue={selected.expiresAt||""} required/></label><button className="primary">Save expiry date</button></form><p className="hint">Set a member to active only after payment or approval is confirmed.</p></section>
      <section className="panel qr-panel"><h2>Digital membership card</h2><div className="season-pass"><img className="season-art" src="/township-rollers-season-ticket.jpg" alt="Township Rollers 2026–2027 season ticket artwork with club crest, cheering fans and sponsor strip"/><div className="pass-content"><span className="pass-label">SEASONAL ACCESS PASS</span><strong className="pass-name">{selected.firstName} {selected.lastName}</strong><span className="pass-id">{selected.id}</span><div className="pass-qr">{qr?<img src={qr} alt="QR code linking to current membership verification"/>:<span>QR unavailable</span>}</div><span className={"pass-status "+selected.status}>{selected.status.toUpperCase()}</span></div></div><p><a href={"/member/"+selected.token} target="_blank" rel="noopener noreferrer">Open member portal →</a></p><p className="hint">The QR opens a live status check. Changes here appear at verification.</p><button className="secondary" onClick={()=>{navigator.clipboard.writeText(location.origin+"/verify/"+selected.token);setNotice("Verification link copied")}}><Copy size={16}/> Copy verification link</button></section></div>
      <section className="panel"><h2>Member messages</h2>{data.notifications.filter(n=>n.memberId===selected.id).length?data.notifications.filter(n=>n.memberId===selected.id).map(n=><article className="admin-message" key={n.id}><small>{new Date(n.createdAt).toLocaleString("en-BW")}</small><strong>{n.title}</strong><p>{n.body}</p>{n.reply?<div className="member-reply"><b>Member response</b><p>{n.reply}</p><small>{n.repliedAt?new Date(n.repliedAt).toLocaleString("en-BW"):""}</small></div>:<span className="awaiting-reply">Awaiting response</span>}</article>):<p className="muted">No personal notifications sent yet.</p>}</section><section className="panel"><h2>Assigned promotional codes</h2>{data.promos.filter(p=>p.memberId===selected.id).length?<div className="chips">{data.promos.filter(p=>p.memberId===selected.id).map(p=><span key={p.code}>{p.code} <small>· {p.campaign}</small></span>)}</div>:<p className="muted">No codes assigned to this member.</p>}</section></>:
    tab==="members"?<><div className="page-head"><div><p className="eyebrow">SUPPORTER REGISTRY</p><h1>Members</h1><p className="sub">Manage membership records and verify current status.</p></div><button className="primary" onClick={()=>setShowForm(!showForm)}><Plus size={18}/> Add member</button></div>
      <div className="stats"><div><small>TOTAL MEMBERS</small><strong>{data.members.length}</strong></div><div><small>ACTIVE</small><strong>{data.members.filter(m=>m.status==="active").length}</strong></div><div><small>PENDING</small><strong>{data.members.filter(m=>m.status==="pending").length}</strong></div></div>
      {showForm&&<section className="panel form-panel"><h2>New member</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:"member",firstName:f.get("firstName"),lastName:f.get("lastName"),phone:f.get("phone"),email:f.get("email"),expiresAt:f.get("expiresAt")},"Member added with pending status"))setShowForm(false)}}><div className="form-grid"><label>First name<input name="firstName" required maxLength={80}/></label><label>Last name<input name="lastName" required maxLength={80}/></label><label>Phone<input name="phone" type="tel"/></label><label>Email<input name="email" type="email"/></label><label>Expiry date<input name="expiresAt" type="date"/></label></div><div className="form-actions"><button className="primary">Save member</button><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button></div></form></section>}
      <section className="panel"><div className="panel-head"><div><h2>Member directory</h2><p>{list.length} records</p></div><label className="search"><Search size={18}/><input placeholder="Search name, ID or phone" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search members"/></label></div><div className="table-wrap"><table><thead><tr><th>MEMBER</th><th>MEMBER ID</th><th>CONTACT</th><th>STATUS</th><th>EXPIRY</th><th></th></tr></thead><tbody>{list.map(m=><tr key={m.id}><td><b>{m.firstName} {m.lastName}</b></td><td className="mono">{m.id}</td><td>{m.phone||m.email||"—"}</td><td><Badge status={m.status==="active"&&m.expiresAt&&m.expiresAt<new Date().toISOString().slice(0,10)?"expired":m.status}/></td><td>{m.expiresAt||"—"}</td><td><button className="text-button" onClick={()=>setSelected(m)}>View card →</button></td></tr>)}</tbody></table>{!list.length&&<div className="empty">{loading?"Loading members…":query?"No matching members.":"No members yet. Add the first member to begin."}</div>}</div></section></>:
    tab==="promos"?<><div className="page-head"><div><p className="eyebrow">PARTNER BENEFITS</p><h1>Promotional codes</h1><p className="sub">Load unique codes and assign each one to a member.</p></div></div><section className="partner-card"><div><p className="eyebrow">FEATURED PARTNER</p><h2>Options Botswana</h2><p>Load Options codes separately and assign each unique code to one member.</p><a href="https://www.facebook.com/Optionsbw" target="_blank" rel="noopener noreferrer">Visit partner page ↗</a></div><div className="partner-count"><strong>{data.promos.filter(p=>p.campaign==="Options Botswana").length}</strong><span>Options codes loaded</span></div></section><div className="two-col"><section className="panel"><h2>Load codes</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:"promos",campaign:f.get("campaign"),codes:f.get("codes")},"Codes loaded"))e.currentTarget.reset()}}><label>Partner or campaign<input name="campaign" defaultValue="Options Botswana" required/></label><label>Unique codes<textarea name="codes" rows={7} placeholder={"TR-001\nTR-002\nTR-003"} required/></label><p className="hint">Paste the actual codes supplied by Options, one per line or separated by commas. Duplicates are skipped.</p><button className="primary">Load codes</button></form></section><section className="panel"><h2>Assign an available code</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:"assign",code:f.get("code"),memberId:f.get("memberId")},"Code assigned"))e.currentTarget.reset()}}><label>Promotional code<select name="code" required defaultValue=""><option value="">Select code</option>{data.promos.filter(p=>p.status==="available").map(p=><option key={p.code} value={p.code}>{p.code} · {p.campaign}</option>)}</select></label><label>Member<select name="memberId" required defaultValue=""><option value="">Select member</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.firstName} {m.lastName} · {m.id}</option>)}</select></label><button className="primary">Assign code</button></form></section></div><section className="panel"><div className="panel-head"><h2>Code register</h2><p>{data.promos.length} codes</p></div><div className="table-wrap"><table><thead><tr><th>CODE</th><th>CAMPAIGN</th><th>ASSIGNED TO</th><th>STATUS</th></tr></thead><tbody>{data.promos.map(p=><tr key={p.code}><td className="mono"><b>{p.code}</b></td><td>{p.campaign}</td><td>{p.memberId||"—"}</td><td><Badge status={p.status}/></td></tr>)}</tbody></table>{!data.promos.length&&<div className="empty">No codes loaded yet.</div>}</div></section></>:
    <><div className="page-head"><div><p className="eyebrow">CLUB COMMUNICATION</p><h1>Communiqués</h1><p className="sub">Post internal updates for the membership office.</p></div></div><div className="two-col"><section className="panel"><h2>New update</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:"update",title:f.get("title"),body:f.get("body")},"Update published"))e.currentTarget.reset()}}><label>Title<input name="title" required maxLength={150}/></label><label>Message<textarea name="body" rows={8} required maxLength={3000}/></label><button className="primary">Publish update</button></form><p className="hint">Updates appear here for staff. Member delivery can be connected when sign-in and contact channels are approved.</p></section><section className="panel"><h2>Published updates</h2>{data.updates.length?data.updates.map(u=><article className="update" key={u.id}><small>{new Date(u.createdAt).toLocaleDateString()}</small><h3>{u.title}</h3><p>{u.body}</p></article>):<div className="empty">No updates published yet.</div>}</section></div></>}
    {error&&<div className="toast error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}{notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
   </div>
  </main>
  {mobileMenu&&<div className="mobile-menu-backdrop" role="presentation" onClick={()=>setMobileMenu(false)}><section className="mobile-menu-sheet" role="dialog" aria-modal="true" aria-label="Administration menu" onClick={e=>e.stopPropagation()}><div className="mobile-menu-head"><div><span className="mini-crest">TR</span><b>Administration menu</b></div><button aria-label="Close menu" onClick={()=>setMobileMenu(false)}><X size={24}/></button></div><nav><a href="/club"><Trophy size={22}/><span><b>Club profile</b><small>Fixtures, team, results and updates</small></span></a><a href="/office"><Settings size={22}/><span><b>Club office</b><small>Payments, operations and team administration</small></span></a><a href="/admin-access"><ShieldCheck size={22}/><span><b>Manage administrators</b><small>Executive access and administrator roles</small></span></a><button onClick={async()=>{await fetch("/api/admin-pin",{method:"DELETE"});location.assign("/signout-with-chatgpt?return_to=/")}}><LogOut size={22}/><span><b>Logout</b><small>End this administrator session</small></span></button></nav></section></div>}
  <nav className="mobile-nav" aria-label="Sections"><button className={tab==="members"?"on":""} onClick={()=>{setTab("members");setSelected(null);setMobileMenu(false)}}><Users size={20}/>Members</button><button className={tab==="promos"?"on":""} onClick={()=>{setTab("promos");setSelected(null);setMobileMenu(false)}}><Ticket size={20}/>Codes</button><button className={tab==="updates"?"on":""} onClick={()=>{setTab("updates");setSelected(null);setMobileMenu(false)}}><Megaphone size={20}/>Updates</button><button className={mobileMenu?"on":""} onClick={()=>setMobileMenu(true)} aria-haspopup="dialog"><Menu size={20}/>Menu</button></nav>
 </div>
}
