export const officialMatch = {
  opponent: "Extension Gunners",
  date: "2026-09-20",
  formation: "4-3-3",
  score: "3–0",
  sourceLabel: "Township Rollers FC official Facebook page",
  players: [
    { id: "match-32", firstName: "T.", lastName: "More", squadNumber: 32, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-2", firstName: "P.", lastName: "Moahi", squadNumber: 2, position: "Starting XI", status: "active", lineupRole: "sub_out" },
    { id: "match-6", firstName: "O.", lastName: "Ratanang", squadNumber: 6, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-19", firstName: "T.", lastName: "Secopolo", squadNumber: 19, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-3", firstName: "B.", lastName: "Sebapalo", squadNumber: 3, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-28", firstName: "J.", lastName: "Tapologo", squadNumber: 28, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-22", firstName: "B.", lastName: "Seboko", squadNumber: 22, position: "Starting XI", status: "active", lineupRole: "sub_out" },
    { id: "match-8", firstName: "M.", lastName: "Papama", squadNumber: 8, position: "Captain", status: "active", lineupRole: "first_eleven" },
    { id: "match-17", firstName: "K.", lastName: "Mokeresete", squadNumber: 17, position: "Starting XI", status: "active", lineupRole: "sub_out" },
    { id: "match-10", firstName: "T.", lastName: "Kgaolo", squadNumber: 10, position: "Starting XI", status: "active", lineupRole: "sub_out" },
    { id: "match-29", firstName: "T.", lastName: "Mogotsi", squadNumber: 29, position: "Starting XI", status: "active", lineupRole: "first_eleven" },
    { id: "match-1", firstName: "P.", lastName: "Kgarathi", squadNumber: 1, position: "Goalkeeper", status: "active", lineupRole: "substitute" },
    { id: "match-15", firstName: "M.", lastName: "Mpotsang", squadNumber: 15, position: "Substitute", status: "active", lineupRole: "substitute" },
    { id: "match-14", firstName: "I.", lastName: "Maketo", squadNumber: 14, position: "Substitute", status: "active", lineupRole: "substitute" },
    { id: "match-23", firstName: "O.", lastName: "Ramotlhwa", squadNumber: 23, position: "Substitute", status: "active", lineupRole: "sub_in" },
    { id: "match-12", firstName: "T.", lastName: "Majingo", squadNumber: 12, position: "Substitute", status: "active", lineupRole: "sub_in" },
    { id: "match-25", firstName: "C.", lastName: "Gaobatelwe", squadNumber: 25, position: "Substitute", status: "active", lineupRole: "sub_in" },
    { id: "match-77", firstName: "M.", lastName: "Moriana", squadNumber: 77, position: "Substitute", status: "active", lineupRole: "sub_in" },
    { id: "match-27", firstName: "W.", lastName: "Dithwane", squadNumber: 27, position: "Substitute", status: "active", lineupRole: "substitute" },
    { id: "match-30", firstName: "K.", lastName: "Koonne", squadNumber: 30, position: "Substitute", status: "active", lineupRole: "substitute" },
  ],
  substitutions: [
    { minute: 37, playerIn: "Thembelani Majingo", playerOut: "Kaone Mokeresete" },
    { minute: 56, playerIn: "Moriana Moriana", playerOut: "Tlotlo Kgaolo" },
    { minute: 74, playerIn: "Ramotlhane", playerOut: "Seboko" },
    { minute: 74, playerIn: "Gaobatelwe", playerOut: "Moah" },
  ],
} as const;
