CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', expires_at TEXT NOT NULL DEFAULT '', token TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, id_number TEXT UNIQUE, date_of_birth TEXT, place_of_birth TEXT, membership_location TEXT, gender TEXT, password_salt TEXT NOT NULL DEFAULT '', password_hash TEXT NOT NULL DEFAULT '', password_must_change BOOLEAN NOT NULL DEFAULT FALSE);
ALTER TABLE members ADD COLUMN IF NOT EXISTS password_salt TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN IF NOT EXISTS password_must_change BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS email_verified_at TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_members_email ON members (lower(email));
CREATE INDEX IF NOT EXISTS idx_members_status ON members (status);
CREATE INDEX IF NOT EXISTS idx_members_location ON members (membership_location);
CREATE INDEX IF NOT EXISTS idx_members_created_at ON members (created_at);
CREATE INDEX IF NOT EXISTS idx_members_email_verified ON members (email_verified_at);

CREATE TABLE IF NOT EXISTS promos (code TEXT PRIMARY KEY, campaign TEXT NOT NULL, member_id TEXT, status TEXT NOT NULL DEFAULT 'available', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS updates (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, amount INTEGER NOT NULL DEFAULT 200, receipt_key TEXT NOT NULL, receipt_name TEXT NOT NULL, receipt_type TEXT NOT NULL, reference TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'submitted', note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, reviewed_at TEXT NOT NULL DEFAULT '');
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reviewed_by TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_payments_member ON payments (member_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments (status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments (created_at);

CREATE TABLE IF NOT EXISTS fixtures (id TEXT PRIMARY KEY, opponent TEXT NOT NULL, kickoff TEXT NOT NULL, venue TEXT NOT NULL, home_away TEXT NOT NULL, competition TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'upcoming', rollers_score INTEGER, opponent_score INTEGER, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS standings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team TEXT NOT NULL UNIQUE, played INTEGER NOT NULL DEFAULT 0, won INTEGER NOT NULL DEFAULT 0, drawn INTEGER NOT NULL DEFAULT 0, lost INTEGER NOT NULL DEFAULT 0, goal_difference INTEGER NOT NULL DEFAULT 0, points INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS club_updates (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS member_notifications (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, reply TEXT NOT NULL DEFAULT '', replied_at TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS players (id TEXT PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL, squad_number INTEGER NOT NULL UNIQUE, position TEXT NOT NULL, contract_type TEXT NOT NULL DEFAULT 'Permanent', contract_start TEXT NOT NULL DEFAULT '', contract_end TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active', lineup_role TEXT NOT NULL DEFAULT 'squad', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS club_settings (id INTEGER PRIMARY KEY, membership_validity_days INTEGER NOT NULL DEFAULT 334, expiry_reminder_days INTEGER NOT NULL DEFAULT 7, updated_at TEXT NOT NULL);
ALTER TABLE club_settings ADD COLUMN IF NOT EXISTS season_name TEXT NOT NULL DEFAULT '2026 / 2027';
ALTER TABLE club_settings ADD COLUMN IF NOT EXISTS season_start_date TEXT NOT NULL DEFAULT '2026-09-01';
ALTER TABLE club_settings ADD COLUMN IF NOT EXISTS season_end_date TEXT NOT NULL DEFAULT '2027-07-31';
ALTER TABLE club_settings ADD COLUMN IF NOT EXISTS membership_fee INTEGER NOT NULL DEFAULT 200;
ALTER TABLE club_settings ADD COLUMN IF NOT EXISTS registration_open INTEGER NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS audit_logs (
 id TEXT PRIMARY KEY,
 actor_email TEXT NOT NULL DEFAULT '',
 actor_name TEXT NOT NULL DEFAULT '',
 actor_role TEXT NOT NULL DEFAULT '',
 action TEXT NOT NULL,
 entity_type TEXT NOT NULL,
 entity_id TEXT NOT NULL,
 before_json TEXT NOT NULL DEFAULT '',
 after_json TEXT NOT NULL DEFAULT '',
 note TEXT NOT NULL DEFAULT '',
 created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
 id TEXT PRIMARY KEY,
 member_id TEXT NOT NULL,
 token_hash TEXT NOT NULL UNIQUE,
 expires_at TEXT NOT NULL,
 used_at TEXT NOT NULL DEFAULT '',
 created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email_verification_member ON email_verification_tokens (member_id, created_at);
CREATE INDEX IF NOT EXISTS idx_email_verification_expiry ON email_verification_tokens (expires_at);

CREATE TABLE IF NOT EXISTS email_delivery_log (
 id TEXT PRIMARY KEY,
 recipient TEXT NOT NULL,
 template TEXT NOT NULL,
 subject TEXT NOT NULL,
 provider_message_id TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL,
 error TEXT NOT NULL DEFAULT '',
 created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email_delivery_recipient ON email_delivery_log (recipient, created_at);
CREATE INDEX IF NOT EXISTS idx_email_delivery_status ON email_delivery_log (status, created_at);

CREATE TABLE IF NOT EXISTS password_recovery_requests (
 id TEXT PRIMARY KEY,
 member_id TEXT NOT NULL,
 email TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending',
 requested_at TEXT NOT NULL,
 resolved_at TEXT NOT NULL DEFAULT '',
 resolved_by TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_password_recovery_status ON password_recovery_requests (status, requested_at);
CREATE INDEX IF NOT EXISTS idx_password_recovery_member ON password_recovery_requests (member_id);

CREATE TABLE IF NOT EXISTS admin_users (email TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, pin_salt TEXT NOT NULL DEFAULT '', pin_hash TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_sessions (token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_login_attempts (email TEXT PRIMARY KEY, failed_count INTEGER NOT NULL DEFAULT 0, locked_until TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS member_sessions (token_hash TEXT PRIMARY KEY, member_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS member_login_attempts (email TEXT PRIMARY KEY, failed_count INTEGER NOT NULL DEFAULT 0, locked_until TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL);

INSERT INTO club_settings (id,membership_validity_days,expiry_reminder_days,updated_at,season_name,season_start_date,season_end_date,membership_fee,registration_open)
VALUES (1,334,7,CURRENT_TIMESTAMP::text,'2026 / 2027','2026-09-01','2027-07-31',200,1)
ON CONFLICT (id) DO NOTHING;
