"use client";
import {useEffect,useRef,useState} from "react";
import QRCode from "qrcode";
import Link from "next/link";
import {FixtureCard} from "../../components/fixture-card";
type Member={id:string;firstName:string;lastName:string;status:string;expiresAt:string;token:string;reminderDays?:number};
type Payment={id:string;amount:number;reference:string;status:string;note:string;createdAt:string}|null;
type Fixture={id:string;opponent:string;kickoff:string;venue:string;homeAway:string;competition:string;rollersScore?:number;opponentScore?:number};
type Standing={team:string;played:number;won:number;drawn:number;lost:number;goalDifference:number;points:number};
type Update={id:number;title:string;body:string;createdAt:string};
type DirectNotification={id:number;title:string;body:string;reply:string;repliedAt:string;createdAt:string};
const when=(date:string)=>new Date(date).toLocaleString("en-BW",{dateStyle:"medium",timeStyle:"short"});
export default function MemberPortal({params}:{params:Promise<{token:string}>}){
 const [token,setToken]=useState(""),[member,setMember]=useState<Member|null>(null),[payment,setPayment]=useState<Payment>(null),[club,setClub]=useState<{fixtures:Fixture[];results:Fixture[];standings:Standing[];updates:Update[]}>({fixtures:[],results:[],standings:[],updates:[]}),[directNotifications,setDirectNotifications]=useState<DirectNotification[]>([]),[qr,setQr]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState<"home"|"matches"|"table"|"updates">("home"),[unread,setUnread]=useState(0),[liveNotice,setLiveNotice]=useState("");
 const latestUpdateId=useRef(0);
 const latestDirectId=useRef(0);
 useEffect(()=>{params.then(({token})=>setToken(token))},[params]);
 useEffect(()=>{if(!token)return;Promise.all([fetch("/api/member/"+encodeURIComponent(token),{cache:"no-store"}),fetch("/api/club",{cache:"no-store"})]).then(async([a,b])=>{const m=await a.json() as {error?:string;member:Member;payment:Payment;notifications:DirectNotification[]},c=await b.json() as {error?:string;fixtures:Fixture[];results:Fixture[];standings:Standing[];updates:Update[]};if(!a.ok)throw Error(m.error||"Member not found");if(!b.ok)throw Error(c.error||"Club information unavailable");setMember(m.member);setPayment(m.payment);setDirectNotifications(m.notifications||[]);setClub(c);latestUpdateId.current=Math.max(0,...c.updates.map(u=>u.id));latestDirectId.current=Math.max(0,...(m.notifications||[]).map(u=>u.id));QRCode.toDataURL(location.origin+"/verify/"+token,{width:320,margin:2,color:{dark:"#102b5a",light:"#ffffff"}}).then(setQr)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 useEffect(()=>{if(!token||loading)return;const refresh=async()=>{try{const [clubResponse,memberResponse]=await Promise.all([fetch("/api/club",{cache:"no-store"}),fetch("/api/member/"+encodeURIComponent(token),{cache:"no-store"})]);if(!clubResponse.ok||!memberResponse.ok)return;const next=await clubResponse.json() as {fixtures:Fixture[];results:Fixture[];standings:Standing[];updates:Update[]};const memberData=await memberResponse.json() as {notifications:DirectNotification[]};const newest=Math.max(0,...next.updates.map(u=>u.id));const newestDirect=Math.max(0,...(memberData.notifications||[]).map(u=>u.id));const freshClub=next.updates.filter(u=>u.id>latestUpdateId.current);const freshDirect=(memberData.notifications||[]).filter(u=>u.id>latestDirectId.current);if(freshClub.length||freshDirect.length){setUnread(n=>n+freshClub.length+freshDirect.length);setLiveNotice(freshDirect[0]?.title||freshClub[0]?.title||"New notification");window.setTimeout(()=>setLiveNotice(""),6000)}latestUpdateId.current=newest;latestDirectId.current=newestDirect;setClub(next);setDirectNotifications(memberData.notifications||[])}catch{}};const timer=window.setInterval(refresh,10000);return()=>window.clearInterval(timer)},[token,loading]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setSuccess("");setBusy(true);try{const body=new FormData(e.currentTarget);const r=await fetch("/api/member/"+encodeURIComponent(token),{method:"POST",body});const result=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(result.error);setSuccess("Proof received. The club will review it before activating your membership.");setPayment({id:result.id,amount:200,reference:String(body.get("reference")||""),status:"submitted",note:"",createdAt:new Date().toISOString()});e.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
 async function replyToNotification(e:React.FormEvent<HTMLFormElement>,id:number){e.preventDefault();const form=e.currentTarget,reply=String(new FormData(form).get("reply")||"").trim();if(!reply)return;setBusy(true);setError("");try{const r=await fetch("/api/member/"+encodeURIComponent(token),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"notification-reply",id,reply})});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error);setDirectNotifications(current=>current.map(n=>n.id===id?{...n,reply,repliedAt:new Date().toISOString()}:n));setSuccess("Your response was sent to the membership office.");form.reset()}catch(e){setError(e instanceof Error?e.message:"Response could not be sent.")}finally{setBusy(false)}}
 const effectiveStatus=member?.status==="active"&&member.expiresAt&&member.expiresAt<new Date().toISOString().slice(0,10)?"expired":member?.status;
 const daysRemaining=member?.expiresAt?Math.ceil((new Date(member.expiresAt+"T23:59:59").getTime()-Date.now())/86400000):null;
 return <main className="member-shell"><header className="member-header"><Link href="/club" className="member-brand"><span className="mini-crest">TR</span><span>TOWNSHIP ROLLERS FC</span></Link><div className="member-header-actions"><span>2026 / 2027</span><a href="/member-logout">Sign out</a></div></header>
  <nav className="member-tabs" aria-label="Member portal"><button className={tab==="home"?"current":""} onClick={()=>setTab("home")}>My membership</button><button className={tab==="matches"?"current":""} onClick={()=>setTab("matches")}>Matches</button><button className={tab==="table"?"current":""} onClick={()=>setTab("table")}>Standings</button><button className={tab==="updates"?"current":""} onClick={()=>{setTab("updates");setUnread(0)}}>Club updates {unread>0&&<span className="live-count" aria-label={`${unread} new updates`}>{unread}</span>}</button></nav>
  <div className="member-content">{loading?<section className="member-panel">Loading your membership…</section>:!member?<section className="member-panel" role="alert">{error||"Member record not found."}</section>:<>
   {tab==="home"&&<><div className="member-heading"><div><p className="eyebrow">MY MEMBERSHIP</p><h1>Welcome to Township Rollers FC</h1><p>Member ID {member.id}</p></div><span className={"badge "+effectiveStatus}>{effectiveStatus}</span></div>{effectiveStatus==="expired"?<div className="expiry-alert expired"><strong>Membership expired</strong><span>Expired on {new Date(member.expiresAt+"T00:00:00").toLocaleDateString("en-BW",{dateStyle:"long"})}. Upload proof of renewal payment to reactivate it.</span></div>:effectiveStatus==="active"&&daysRemaining!==null&&daysRemaining<=Number(member.reminderDays||7)?<div className="expiry-alert warning"><strong>Membership expires soon</strong><span>{daysRemaining<=0?"Expires today":`${daysRemaining} day${daysRemaining===1?"":"s"} remaining`} · Renewal is P200.</span></div>:null}<div className="member-columns"><section className="member-panel"><h2>Digital season card</h2><div className="season-pass"><img className="season-art" src="/township-rollers-season-ticket.jpg" alt="Township Rollers 2026–2027 season ticket artwork"/><div className="pass-content"><span className="pass-label">SEASONAL ACCESS PASS</span><strong className="pass-name">{member.firstName} {member.lastName}</strong><span className="pass-id">{member.id}</span><div className="pass-qr">{qr?<img src={qr} alt="QR code for live membership verification"/>:"QR unavailable"}</div><span className={"pass-status "+effectiveStatus}>{effectiveStatus?.toUpperCase()}</span></div></div><p className="muted">The QR checks your current membership status. Keep this link private.</p></section><section className="member-panel"><h2>P200 season membership</h2><p className="member-amount">P200 <small>per member</small></p><p>Pay using the club’s official payment instructions, then upload a clear receipt here. The club will confirm it before your card becomes active.</p><p className="muted">Payment details will be shared by the club. Do not send money to an account shown outside its official channels.</p>{payment&&<div className="payment-state"><span className={"badge "+payment.status}>{payment.status}</span><p>Submitted {when(payment.createdAt)}</p>{payment.note&&<p>Club note: {payment.note}</p>}</div>}{effectiveStatus!=="active"&&(effectiveStatus==="expired"||!payment||payment.status==="rejected")&&<form onSubmit={submit} className="proof-form"><label>Payment reference (optional)<input name="reference" maxLength={100} placeholder="Transaction reference"/></label><label>Proof of payment<input name="proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label><p className="muted">JPG, PNG, WebP or PDF · maximum 5 MB</p><button disabled={busy} className="primary">{busy?"Uploading…":"Submit proof for review"}</button></form>}{success&&<p className="form-success" role="status">{success}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</section></div></>}
   {tab==="matches"&&<><div className="member-heading"><h1>Matches</h1></div><div className="member-columns"><section className="member-panel"><h2>Upcoming fixtures</h2>{club.fixtures.length?club.fixtures.map(f=><FixtureCard key={f.id} fixture={f}/>):<p className="muted">No fixtures published yet.</p>}</section><section className="member-panel results-panel"><h2>Previous results</h2>{club.results.length?club.results.map(f=><article className="match-row result-card" key={f.id}><strong>{f.homeAway==="away"?`${f.opponent} ${f.opponentScore} – ${f.rollersScore} Township Rollers`:`Township Rollers ${f.rollersScore} – ${f.opponentScore} ${f.opponent}`}</strong><span>{when(f.kickoff)} · {f.venue}</span><small>{f.competition}</small></article>):<p className="muted">No results published yet.</p>}</section></div></>}
   {tab==="table"&&<section className="member-panel standings-panel"><h1>League standings</h1><p className="muted">Updated by the club. Move over a team row to highlight it.</p><div className="table-wrap standings-table"><table><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th></tr></thead><tbody>{club.standings.map((s,i)=><tr key={s.team} className={s.team.toLowerCase().includes("township rollers")?"rollers-row":""}><td>{i+1}</td><td><b>{s.team}</b></td><td>{s.played}</td><td>{s.won}</td><td>{s.drawn}</td><td>{s.lost}</td><td>{s.goalDifference}</td><td><b>{s.points}</b></td></tr>)}</tbody></table>{!club.standings.length&&<p className="muted">No league table published yet.</p>}</div></section>}
   {tab==="updates"&&<section className="member-panel"><h1>Club updates</h1>{success&&<p className="form-success" role="status">{success}</p>}{error&&<p className="form-error" role="alert">{error}</p>}{directNotifications.map(u=><article className="update direct-update" key={"member-"+u.id}><small>PERSONAL NOTIFICATION · {when(u.createdAt)}</small><h3>{u.title}</h3><p>{u.body}</p>{u.reply?<div className="sent-reply"><strong>Your response</strong><p>{u.reply}</p><small>Sent {when(u.repliedAt)}</small></div>:<form className="notification-reply" onSubmit={e=>void replyToNotification(e,u.id)}><label>Respond to the membership office<textarea name="reply" maxLength={1000} required placeholder="Type your response…"/></label><button className="primary" disabled={busy}>{busy?"Sending…":"Send response"}</button></form>}</article>)}{club.updates.map(u=><article className="update" key={"club-"+u.id}><small>{when(u.createdAt)}</small><h3>{u.title}</h3><p>{u.body}</p></article>)}{!directNotifications.length&&!club.updates.length&&<p className="muted">No club updates published yet.</p>}</section>}
  </>}</div>{liveNotice&&<button className="live-notification" role="status" onClick={()=>{setTab("updates");setUnread(0);setLiveNotice("")}}><span>NEW CLUB UPDATE</span><strong>{liveNotice}</strong><small>Tap to read</small></button>}</main>
}
